import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: The Python LangGraph adapter declares protocolVersion 1.0 on RUN_STARTED, as the versioning rules require of a 1.0 producer; every recorded run boundary gains the field, nothing else changes.
// Before accepting changes, verify whether the implementation regressed.
const shared1 =
  '{"temperature": 20, "conditions": "sunny", "humidity": 50, "wind_speed": 10, "feelsLike": 25}' as const;
const shared2 = {
  output: {
    messages: [
      {
        content: "Done! I've completed that for you.",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-32",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
  },
  input: {
    messages: [
      {
        content: "What's the weather like in San Francisco?",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-4",
        tool_calls: [
          {
            name: "get_weather",
            args: {
              location: "San Francisco",
            },
            id: "id-5",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: shared1,
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: "get_weather",
        id: "id-19",
        tool_call_id: "id-5",
        artifact: null,
        status: "success",
      },
      {
        content: "Done! I've completed that for you.",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-14",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Tell me about the weather in New York.",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-22",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-23",
        tool_calls: [
          {
            name: "get_weather",
            args: {
              location: "San Francisco",
            },
            id: "id-5",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: shared1,
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: "get_weather",
        id: "id-37",
        tool_call_id: "id-5",
        artifact: null,
        status: "success",
      },
    ],
    remaining_steps: 22,
  },
} as const;
const shared3 = {
  output: {
    messages: [
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-23",
        tool_calls: [
          {
            name: "get_weather",
            args: {
              location: "San Francisco",
            },
            id: "id-5",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
  },
  input: {
    messages: [
      {
        content: "What's the weather like in San Francisco?",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-4",
        tool_calls: [
          {
            name: "get_weather",
            args: {
              location: "San Francisco",
            },
            id: "id-5",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: shared1,
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: "get_weather",
        id: "id-19",
        tool_call_id: "id-5",
        artifact: null,
        status: "success",
      },
      {
        content: "Done! I've completed that for you.",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-14",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: "Tell me about the weather in New York.",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-22",
      },
    ],
    remaining_steps: 24,
  },
} as const;
const shared4 = {
  output: {
    messages: [
      {
        content: "Done! I've completed that for you.",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "stop",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-14",
        tool_calls: [],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
  },
  input: {
    messages: [
      {
        content: "What's the weather like in San Francisco?",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-4",
        tool_calls: [
          {
            name: "get_weather",
            args: {
              location: "San Francisco",
            },
            id: "id-5",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      {
        content: shared1,
        additional_kwargs: {},
        response_metadata: {},
        type: "tool",
        name: "get_weather",
        id: "id-19",
        tool_call_id: "id-5",
        artifact: null,
        status: "success",
      },
    ],
    remaining_steps: 22,
  },
} as const;
const shared5 = {
  messages: [
    {
      content: "What's the weather like in San Francisco?",
      additional_kwargs: {},
      response_metadata: {},
      type: "human",
      name: null,
      id: "id-3",
    },
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "tool_calls",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [
        {
          name: "get_weather",
          args: {
            location: "San Francisco",
          },
          id: "id-5",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
    {
      content: shared1,
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: "get_weather",
      id: "id-19",
      tool_call_id: "id-5",
      artifact: null,
      status: "success",
    },
    {
      content: "Done! I've completed that for you.",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-14",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
} as const;
const shared6 = {
  event: "on_chat_model_stream",
  data: {
    chunk: {
      content: "Done! I've completed",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
      },
      type: "AIMessageChunk",
      name: null,
      id: "id-32",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
      tool_call_chunks: [],
      chunk_position: null,
    },
  },
  run_id: "id-33",
  name: "ChatOpenAI",
  tags: ["seq:step:2"],
  metadata: {
    thread_id: "id-1",
    ls_integration: "langchain_chat_model",
    langgraph_step: 8,
    langgraph_node: "agent",
    langgraph_triggers: ["branch:to:agent"],
    langgraph_path: ["__pregel_pull", "agent"],
    langgraph_checkpoint_ns: "agent:id-34",
    checkpoint_ns: "agent:id-34",
    ls_provider: "openai",
    ls_model_name: "gpt-4.1-mini",
    ls_model_type: "chat",
    ls_temperature: null,
  },
  parent_ids: ["id-26", "id-35", "id-36"],
} as const;
const shared7 = {
  event: "on_chat_model_stream",
  data: {
    chunk: {
      content: "Done! I've completed",
      additional_kwargs: {},
      response_metadata: {
        model_provider: "openai",
      },
      type: "AIMessageChunk",
      name: null,
      id: "id-14",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
      tool_call_chunks: [],
      chunk_position: null,
    },
  },
  run_id: "id-15",
  name: "ChatOpenAI",
  tags: ["seq:step:2"],
  metadata: {
    thread_id: "id-1",
    ls_integration: "langchain_chat_model",
    langgraph_step: 3,
    langgraph_node: "agent",
    langgraph_triggers: ["branch:to:agent"],
    langgraph_path: ["__pregel_pull", "agent"],
    langgraph_checkpoint_ns: "agent:id-16",
    checkpoint_ns: "agent:id-16",
    ls_provider: "openai",
    ls_model_name: "gpt-4.1-mini",
    ls_model_type: "chat",
    ls_temperature: null,
  },
  parent_ids: ["id-8", "id-17", "id-18"],
} as const;
const shared8 = {
  output: {
    messages: [
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-4",
        tool_calls: [
          {
            name: "get_weather",
            args: {
              location: "San Francisco",
            },
            id: "id-5",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
  },
  input: {
    messages: [
      {
        content: "What's the weather like in San Francisco?",
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
    ],
    remaining_steps: 24,
  },
} as const;
const shared9 = {
  thread_id: "id-1",
  ls_integration: "langchain_chat_model",
  langgraph_step: 6,
  langgraph_node: "agent",
  langgraph_triggers: ["branch:to:agent"],
  langgraph_path: ["__pregel_pull", "agent"],
  langgraph_checkpoint_ns: "agent:id-25",
  checkpoint_ns: "agent:id-25",
  ls_provider: "openai",
  ls_model_name: "gpt-4.1-mini",
  ls_model_type: "chat",
  ls_temperature: null,
} as const;
const shared10 = {
  messages: [
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "tool_calls",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-23",
      tool_calls: [
        {
          name: "get_weather",
          args: {
            location: "San Francisco",
          },
          id: "id-5",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  tools: [],
} as const;
const shared11 = {
  thread_id: "id-1",
  ls_integration: "langchain_chat_model",
  langgraph_step: 1,
  langgraph_node: "agent",
  langgraph_triggers: ["branch:to:agent"],
  langgraph_path: ["__pregel_pull", "agent"],
  langgraph_checkpoint_ns: "agent:id-7",
  checkpoint_ns: "agent:id-7",
  ls_provider: "openai",
  ls_model_name: "gpt-4.1-mini",
  ls_model_type: "chat",
  ls_temperature: null,
} as const;
const shared12 = {
  messages: [
    {
      content: "",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "tool_calls",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-4",
      tool_calls: [
        {
          name: "get_weather",
          args: {
            location: "San Francisco",
          },
          id: "id-5",
          type: "tool_call",
        },
      ],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  tools: [],
} as const;
const shared13 = {
  messages: [
    {
      content: "Done! I've completed that for you.",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-14",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  tools: [],
} as const;
const shared14 = {
  messages: [
    {
      content: "Done! I've completed that for you.",
      additional_kwargs: {},
      response_metadata: {
        finish_reason: "stop",
        model_name: "gpt-4.1-mini",
        model_provider: "openai",
      },
      type: "ai",
      name: null,
      id: "id-32",
      tool_calls: [],
      invalid_tool_calls: [],
      usage_metadata: null,
    },
  ],
  tools: [],
} as const;
const shared15 = {
  messages: [
    {
      content: shared1,
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: "get_weather",
      id: null,
      tool_call_id: "id-5",
      artifact: null,
      status: "success",
    },
  ],
  tools: [],
} as const;
const shared16 = {
  messages: [
    {
      content: shared1,
      additional_kwargs: {},
      response_metadata: {},
      type: "tool",
      name: "get_weather",
      id: null,
      tool_call_id: "id-5",
      artifact: null,
      status: "success",
    },
  ],
} as const;
const shared17 = {
  thread_id: "id-1",
  ls_integration: "langgraph",
  langgraph_step: 3,
  langgraph_node: "agent",
  langgraph_triggers: ["branch:to:agent"],
  langgraph_path: ["__pregel_pull", "agent"],
  langgraph_checkpoint_ns: "agent:id-16",
} as const;
const shared18 = {
  thread_id: "id-1",
  ls_integration: "langgraph",
  langgraph_step: 6,
  langgraph_node: "agent",
  langgraph_triggers: ["branch:to:agent"],
  langgraph_path: ["__pregel_pull", "agent"],
  langgraph_checkpoint_ns: "agent:id-25",
} as const;
const shared19 = {
  thread_id: "id-1",
  ls_integration: "langgraph",
  langgraph_step: 8,
  langgraph_node: "agent",
  langgraph_triggers: ["branch:to:agent"],
  langgraph_path: ["__pregel_pull", "agent"],
  langgraph_checkpoint_ns: "agent:id-34",
} as const;
const shared20 = {
  thread_id: "id-1",
  ls_integration: "langgraph",
  langgraph_step: 1,
  langgraph_node: "agent",
  langgraph_triggers: ["branch:to:agent"],
  langgraph_path: ["__pregel_pull", "agent"],
  langgraph_checkpoint_ns: "agent:id-7",
} as const;
const shared21 = {
  type: "TOOL_CALL_RESULT",
  messageId: "id-5",
  toolCallId: "id-5",
  content: shared1,
  role: "tool",
} as const;
const shared22 = {
  id: "id-4",
  role: "assistant",
  content: "",
  toolCalls: [
    {
      id: "id-5",
      type: "function",
      function: {
        name: "get_weather",
        arguments: '{"location": "San Francisco"}',
      },
    },
  ],
} as const;
const shared23 = {
  id: "id-19",
  content: shared1,
  role: "tool",
  toolCallId: "id-5",
} as const;
const shared24 = {
  content: "You are a helpful assistant",
  additional_kwargs: {},
  response_metadata: {},
  type: "system",
  name: null,
  id: null,
} as const;
const shared25 = [
  {
    name: null,
    args: '{"location":"San Fra',
    id: null,
    index: 0,
    type: "tool_call_chunk",
  },
] as const;
const shared26 = [
  {
    name: null,
    args: 'ncisco"}',
    id: null,
    error: null,
    type: "invalid_tool_call",
  },
] as const;
const shared27 = {
  id: "id-3",
  role: "user",
  content: "What's the weather like in San Francisco?",
} as const;
const shared28 = [
  {
    name: "get_weather",
    args: "",
    id: "id-5",
    index: 0,
    type: "tool_call_chunk",
  },
] as const;

export const backendToolRenderingPageEventTrace = defineEventTrace(
  import.meta.url,
  {
    backendToolRenderingDisplaysWeatherCards: [
      {
        type: "RUN_STARTED",
        threadId: "id-1",
        runId: "id-2",
        protocolVersion: "1.0",
        input: {
          threadId: "id-1",
          runId: "id-2",
          state: {},
          messages: [shared27],
          tools: [],
          context: [],
          forwardedProps: {},
        },
      },
      {
        type: "STEP_STARTED",
        stepName: "agent",
      },
      {
        type: "TOOL_CALL_START",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-4",
              tool_calls: [
                {
                  name: "get_weather",
                  args: {},
                  id: "id-5",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: shared28,
              chunk_position: null,
            },
          },
          run_id: "id-6",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: shared11,
          parent_ids: ["id-8", "id-9", "id-10"],
        },
        toolCallId: "id-5",
        toolCallName: "get_weather",
        parentMessageId: "id-4",
      },
      {
        type: "TOOL_CALL_ARGS",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-4",
              tool_calls: [
                {
                  name: "",
                  args: {
                    location: "San Fra",
                  },
                  id: null,
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: shared25,
              chunk_position: null,
            },
          },
          run_id: "id-6",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: shared11,
          parent_ids: ["id-8", "id-9", "id-10"],
        },
        toolCallId: "id-5",
        delta: '{"location":"San Fra',
      },
      {
        type: "TOOL_CALL_ARGS",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-4",
              tool_calls: [],
              invalid_tool_calls: shared26,
              usage_metadata: null,
              tool_call_chunks: [
                {
                  name: null,
                  args: 'ncisco"}',
                  id: null,
                  index: 0,
                  type: "tool_call_chunk",
                },
              ],
              chunk_position: null,
            },
          },
          run_id: "id-6",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: shared11,
          parent_ids: ["id-8", "id-9", "id-10"],
        },
        toolCallId: "id-5",
        delta: 'ncisco"}',
      },
      {
        type: "TOOL_CALL_END",
        rawEvent: {
          event: "on_chat_model_end",
          data: {
            output: {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-4",
              tool_calls: [
                {
                  name: "get_weather",
                  args: {
                    location: "San Francisco",
                  },
                  id: "id-5",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            input: {
              messages: [
                [
                  shared24,
                  {
                    content: "What's the weather like in San Francisco?",
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "human",
                    name: null,
                    id: "id-3",
                  },
                ],
              ],
            },
          },
          run_id: "id-6",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: shared11,
          parent_ids: ["id-8", "id-9", "id-10"],
        },
        toolCallId: "id-5",
      },
      {
        type: "STATE_SNAPSHOT",
        rawEvent: {
          event: "on_chain_end",
          data: shared8,
          run_id: "id-11",
          name: "call_model",
          tags: ["seq:step:1"],
          metadata: shared20,
          parent_ids: ["id-8", "id-9"],
        },
        snapshot: shared12,
      },
      {
        type: "STATE_SNAPSHOT",
        rawEvent: {
          event: "on_chain_end",
          data: shared8,
          run_id: "id-9",
          name: "agent",
          tags: ["graph:step:1"],
          metadata: shared20,
          parent_ids: ["id-8"],
        },
        snapshot: shared12,
      },
      {
        type: "STEP_FINISHED",
        stepName: "agent",
      },
      {
        type: "STEP_STARTED",
        stepName: "tools",
      },
      shared21,
      {
        type: "STATE_SNAPSHOT",
        rawEvent: {
          event: "on_chain_end",
          data: {
            output: shared16,
            input: {
              __type: "tool_call_with_context",
              tool_call: {
                name: "get_weather",
                args: {
                  location: "San Francisco",
                },
                id: "id-5",
                type: "tool_call",
              },
              state: {
                messages: [
                  {
                    content: "What's the weather like in San Francisco?",
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "human",
                    name: null,
                    id: "id-3",
                  },
                  {
                    content: "",
                    additional_kwargs: {},
                    response_metadata: {
                      finish_reason: "tool_calls",
                      model_name: "gpt-4.1-mini",
                      model_provider: "openai",
                    },
                    type: "ai",
                    name: null,
                    id: "id-4",
                    tool_calls: [
                      {
                        name: "get_weather",
                        args: {
                          location: "San Francisco",
                        },
                        id: "id-5",
                        type: "tool_call",
                      },
                    ],
                    invalid_tool_calls: [],
                    usage_metadata: null,
                  },
                ],
                remaining_steps: 24,
              },
            },
          },
          run_id: "id-12",
          name: "tools",
          tags: ["graph:step:2"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langgraph",
            langgraph_step: 2,
            langgraph_node: "tools",
            langgraph_triggers: ["__pregel_push"],
            langgraph_path: ["__pregel_push", 0, false],
            langgraph_checkpoint_ns: "tools:id-13",
          },
          parent_ids: ["id-8"],
        },
        snapshot: shared15,
      },
      {
        type: "STEP_FINISHED",
        stepName: "tools",
      },
      {
        type: "STEP_STARTED",
        stepName: "agent",
      },
      {
        type: "TEXT_MESSAGE_START",
        rawEvent: shared7,
        messageId: "id-14",
        role: "assistant",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: shared7,
        messageId: "id-14",
        delta: "Done! I've completed",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: " that for you.",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-14",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: [],
              chunk_position: null,
            },
          },
          run_id: "id-15",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 3,
            langgraph_node: "agent",
            langgraph_triggers: ["branch:to:agent"],
            langgraph_path: ["__pregel_pull", "agent"],
            langgraph_checkpoint_ns: "agent:id-16",
            checkpoint_ns: "agent:id-16",
            ls_provider: "openai",
            ls_model_name: "gpt-4.1-mini",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-8", "id-17", "id-18"],
        },
        messageId: "id-14",
        delta: " that for you.",
      },
      {
        type: "TEXT_MESSAGE_END",
        rawEvent: {
          event: "on_chat_model_end",
          data: {
            output: {
              content: "Done! I've completed that for you.",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-14",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            input: {
              messages: [
                [
                  shared24,
                  {
                    content: "What's the weather like in San Francisco?",
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "human",
                    name: null,
                    id: "id-3",
                  },
                  {
                    content: "",
                    additional_kwargs: {},
                    response_metadata: {
                      finish_reason: "tool_calls",
                      model_name: "gpt-4.1-mini",
                      model_provider: "openai",
                    },
                    type: "ai",
                    name: null,
                    id: "id-4",
                    tool_calls: [
                      {
                        name: "get_weather",
                        args: {
                          location: "San Francisco",
                        },
                        id: "id-5",
                        type: "tool_call",
                      },
                    ],
                    invalid_tool_calls: [],
                    usage_metadata: null,
                  },
                  {
                    content: shared1,
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "tool",
                    name: "get_weather",
                    id: "id-19",
                    tool_call_id: "id-5",
                    artifact: null,
                    status: "success",
                  },
                ],
              ],
            },
          },
          run_id: "id-15",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 3,
            langgraph_node: "agent",
            langgraph_triggers: ["branch:to:agent"],
            langgraph_path: ["__pregel_pull", "agent"],
            langgraph_checkpoint_ns: "agent:id-16",
            checkpoint_ns: "agent:id-16",
            ls_provider: "openai",
            ls_model_name: "gpt-4.1-mini",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-8", "id-17", "id-18"],
        },
        messageId: "id-14",
      },
      {
        type: "STATE_SNAPSHOT",
        rawEvent: {
          event: "on_chain_end",
          data: shared4,
          run_id: "id-20",
          name: "call_model",
          tags: ["seq:step:1"],
          metadata: shared17,
          parent_ids: ["id-8", "id-17"],
        },
        snapshot: shared13,
      },
      {
        type: "STATE_SNAPSHOT",
        rawEvent: {
          event: "on_chain_end",
          data: shared4,
          run_id: "id-17",
          name: "agent",
          tags: ["graph:step:3"],
          metadata: shared17,
          parent_ids: ["id-8"],
        },
        snapshot: shared13,
      },
      {
        type: "STEP_FINISHED",
        stepName: "agent",
      },
      {
        type: "STATE_SNAPSHOT",
        snapshot: shared5,
      },
      {
        type: "MESSAGES_SNAPSHOT",
        messages: [
          shared27,
          shared22,
          shared23,
          {
            id: "id-14",
            role: "assistant",
            content: "Done! I've completed that for you.",
          },
        ],
      },
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-2",
      },
      {
        type: "RUN_STARTED",
        threadId: "id-1",
        runId: "id-21",
        protocolVersion: "1.0",
        input: {
          threadId: "id-1",
          runId: "id-21",
          state: shared5,
          messages: [
            shared22,
            shared23,
            {
              id: "id-22",
              role: "user",
              content: "Tell me about the weather in New York.",
            },
          ],
          tools: [],
          context: [],
          forwardedProps: {},
        },
      },
      {
        type: "STEP_STARTED",
        stepName: "agent",
      },
      {
        type: "TOOL_CALL_START",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-23",
              tool_calls: [
                {
                  name: "get_weather",
                  args: {},
                  id: "id-5",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: shared28,
              chunk_position: null,
            },
          },
          run_id: "id-24",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: shared9,
          parent_ids: ["id-26", "id-27", "id-28"],
        },
        toolCallId: "id-5",
        toolCallName: "get_weather",
        parentMessageId: "id-23",
      },
      {
        type: "TOOL_CALL_ARGS",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-23",
              tool_calls: [
                {
                  name: "",
                  args: {
                    location: "San Fra",
                  },
                  id: null,
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: shared25,
              chunk_position: null,
            },
          },
          run_id: "id-24",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: shared9,
          parent_ids: ["id-26", "id-27", "id-28"],
        },
        toolCallId: "id-5",
        delta: '{"location":"San Fra',
      },
      {
        type: "TOOL_CALL_ARGS",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-23",
              tool_calls: [],
              invalid_tool_calls: shared26,
              usage_metadata: null,
              tool_call_chunks: [
                {
                  name: null,
                  args: 'ncisco"}',
                  id: null,
                  index: 0,
                  type: "tool_call_chunk",
                },
              ],
              chunk_position: null,
            },
          },
          run_id: "id-24",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: shared9,
          parent_ids: ["id-26", "id-27", "id-28"],
        },
        toolCallId: "id-5",
        delta: 'ncisco"}',
      },
      {
        type: "TOOL_CALL_END",
        rawEvent: {
          event: "on_chat_model_end",
          data: {
            output: {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-23",
              tool_calls: [
                {
                  name: "get_weather",
                  args: {
                    location: "San Francisco",
                  },
                  id: "id-5",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            input: {
              messages: [
                [
                  shared24,
                  {
                    content: "What's the weather like in San Francisco?",
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "human",
                    name: null,
                    id: "id-3",
                  },
                  {
                    content: "",
                    additional_kwargs: {},
                    response_metadata: {
                      finish_reason: "tool_calls",
                      model_name: "gpt-4.1-mini",
                      model_provider: "openai",
                    },
                    type: "ai",
                    name: null,
                    id: "id-4",
                    tool_calls: [
                      {
                        name: "get_weather",
                        args: {
                          location: "San Francisco",
                        },
                        id: "id-5",
                        type: "tool_call",
                      },
                    ],
                    invalid_tool_calls: [],
                    usage_metadata: null,
                  },
                  {
                    content: shared1,
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "tool",
                    name: "get_weather",
                    id: "id-19",
                    tool_call_id: "id-5",
                    artifact: null,
                    status: "success",
                  },
                  {
                    content: "Done! I've completed that for you.",
                    additional_kwargs: {},
                    response_metadata: {
                      finish_reason: "stop",
                      model_name: "gpt-4.1-mini",
                      model_provider: "openai",
                    },
                    type: "ai",
                    name: null,
                    id: "id-14",
                    tool_calls: [],
                    invalid_tool_calls: [],
                    usage_metadata: null,
                  },
                  {
                    content: "Tell me about the weather in New York.",
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "human",
                    name: null,
                    id: "id-22",
                  },
                ],
              ],
            },
          },
          run_id: "id-24",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: shared9,
          parent_ids: ["id-26", "id-27", "id-28"],
        },
        toolCallId: "id-5",
      },
      {
        type: "STATE_SNAPSHOT",
        rawEvent: {
          event: "on_chain_end",
          data: shared3,
          run_id: "id-29",
          name: "call_model",
          tags: ["seq:step:1"],
          metadata: shared18,
          parent_ids: ["id-26", "id-27"],
        },
        snapshot: shared10,
      },
      {
        type: "STATE_SNAPSHOT",
        rawEvent: {
          event: "on_chain_end",
          data: shared3,
          run_id: "id-27",
          name: "agent",
          tags: ["graph:step:6"],
          metadata: shared18,
          parent_ids: ["id-26"],
        },
        snapshot: shared10,
      },
      {
        type: "STEP_FINISHED",
        stepName: "agent",
      },
      {
        type: "STEP_STARTED",
        stepName: "tools",
      },
      shared21,
      {
        type: "STATE_SNAPSHOT",
        rawEvent: {
          event: "on_chain_end",
          data: {
            output: shared16,
            input: {
              __type: "tool_call_with_context",
              tool_call: {
                name: "get_weather",
                args: {
                  location: "San Francisco",
                },
                id: "id-5",
                type: "tool_call",
              },
              state: {
                messages: [
                  {
                    content: "What's the weather like in San Francisco?",
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "human",
                    name: null,
                    id: "id-3",
                  },
                  {
                    content: "",
                    additional_kwargs: {},
                    response_metadata: {
                      finish_reason: "tool_calls",
                      model_name: "gpt-4.1-mini",
                      model_provider: "openai",
                    },
                    type: "ai",
                    name: null,
                    id: "id-4",
                    tool_calls: [
                      {
                        name: "get_weather",
                        args: {
                          location: "San Francisco",
                        },
                        id: "id-5",
                        type: "tool_call",
                      },
                    ],
                    invalid_tool_calls: [],
                    usage_metadata: null,
                  },
                  {
                    content: shared1,
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "tool",
                    name: "get_weather",
                    id: "id-19",
                    tool_call_id: "id-5",
                    artifact: null,
                    status: "success",
                  },
                  {
                    content: "Done! I've completed that for you.",
                    additional_kwargs: {},
                    response_metadata: {
                      finish_reason: "stop",
                      model_name: "gpt-4.1-mini",
                      model_provider: "openai",
                    },
                    type: "ai",
                    name: null,
                    id: "id-14",
                    tool_calls: [],
                    invalid_tool_calls: [],
                    usage_metadata: null,
                  },
                  {
                    content: "Tell me about the weather in New York.",
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "human",
                    name: null,
                    id: "id-22",
                  },
                  {
                    content: "",
                    additional_kwargs: {},
                    response_metadata: {
                      finish_reason: "tool_calls",
                      model_name: "gpt-4.1-mini",
                      model_provider: "openai",
                    },
                    type: "ai",
                    name: null,
                    id: "id-23",
                    tool_calls: [
                      {
                        name: "get_weather",
                        args: {
                          location: "San Francisco",
                        },
                        id: "id-5",
                        type: "tool_call",
                      },
                    ],
                    invalid_tool_calls: [],
                    usage_metadata: null,
                  },
                ],
                remaining_steps: 24,
              },
            },
          },
          run_id: "id-30",
          name: "tools",
          tags: ["graph:step:7"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langgraph",
            langgraph_step: 7,
            langgraph_node: "tools",
            langgraph_triggers: ["__pregel_push"],
            langgraph_path: ["__pregel_push", 0, false],
            langgraph_checkpoint_ns: "tools:id-31",
          },
          parent_ids: ["id-26"],
        },
        snapshot: shared15,
      },
      {
        type: "STEP_FINISHED",
        stepName: "tools",
      },
      {
        type: "STEP_STARTED",
        stepName: "agent",
      },
      {
        type: "TEXT_MESSAGE_START",
        rawEvent: shared6,
        messageId: "id-32",
        role: "assistant",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: shared6,
        messageId: "id-32",
        delta: "Done! I've completed",
      },
      {
        type: "TEXT_MESSAGE_CONTENT",
        rawEvent: {
          event: "on_chat_model_stream",
          data: {
            chunk: {
              content: " that for you.",
              additional_kwargs: {},
              response_metadata: {
                model_provider: "openai",
              },
              type: "AIMessageChunk",
              name: null,
              id: "id-32",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
              tool_call_chunks: [],
              chunk_position: null,
            },
          },
          run_id: "id-33",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 8,
            langgraph_node: "agent",
            langgraph_triggers: ["branch:to:agent"],
            langgraph_path: ["__pregel_pull", "agent"],
            langgraph_checkpoint_ns: "agent:id-34",
            checkpoint_ns: "agent:id-34",
            ls_provider: "openai",
            ls_model_name: "gpt-4.1-mini",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-26", "id-35", "id-36"],
        },
        messageId: "id-32",
        delta: " that for you.",
      },
      {
        type: "TEXT_MESSAGE_END",
        rawEvent: {
          event: "on_chat_model_end",
          data: {
            output: {
              content: "Done! I've completed that for you.",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-32",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            input: {
              messages: [
                [
                  shared24,
                  {
                    content: "What's the weather like in San Francisco?",
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "human",
                    name: null,
                    id: "id-3",
                  },
                  {
                    content: "",
                    additional_kwargs: {},
                    response_metadata: {
                      finish_reason: "tool_calls",
                      model_name: "gpt-4.1-mini",
                      model_provider: "openai",
                    },
                    type: "ai",
                    name: null,
                    id: "id-4",
                    tool_calls: [
                      {
                        name: "get_weather",
                        args: {
                          location: "San Francisco",
                        },
                        id: "id-5",
                        type: "tool_call",
                      },
                    ],
                    invalid_tool_calls: [],
                    usage_metadata: null,
                  },
                  {
                    content: shared1,
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "tool",
                    name: "get_weather",
                    id: "id-19",
                    tool_call_id: "id-5",
                    artifact: null,
                    status: "success",
                  },
                  {
                    content: "Done! I've completed that for you.",
                    additional_kwargs: {},
                    response_metadata: {
                      finish_reason: "stop",
                      model_name: "gpt-4.1-mini",
                      model_provider: "openai",
                    },
                    type: "ai",
                    name: null,
                    id: "id-14",
                    tool_calls: [],
                    invalid_tool_calls: [],
                    usage_metadata: null,
                  },
                  {
                    content: "Tell me about the weather in New York.",
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "human",
                    name: null,
                    id: "id-22",
                  },
                  {
                    content: "",
                    additional_kwargs: {},
                    response_metadata: {
                      finish_reason: "tool_calls",
                      model_name: "gpt-4.1-mini",
                      model_provider: "openai",
                    },
                    type: "ai",
                    name: null,
                    id: "id-23",
                    tool_calls: [
                      {
                        name: "get_weather",
                        args: {
                          location: "San Francisco",
                        },
                        id: "id-5",
                        type: "tool_call",
                      },
                    ],
                    invalid_tool_calls: [],
                    usage_metadata: null,
                  },
                  {
                    content: shared1,
                    additional_kwargs: {},
                    response_metadata: {},
                    type: "tool",
                    name: "get_weather",
                    id: "id-37",
                    tool_call_id: "id-5",
                    artifact: null,
                    status: "success",
                  },
                ],
              ],
            },
          },
          run_id: "id-33",
          name: "ChatOpenAI",
          tags: ["seq:step:2"],
          metadata: {
            thread_id: "id-1",
            ls_integration: "langchain_chat_model",
            langgraph_step: 8,
            langgraph_node: "agent",
            langgraph_triggers: ["branch:to:agent"],
            langgraph_path: ["__pregel_pull", "agent"],
            langgraph_checkpoint_ns: "agent:id-34",
            checkpoint_ns: "agent:id-34",
            ls_provider: "openai",
            ls_model_name: "gpt-4.1-mini",
            ls_model_type: "chat",
            ls_temperature: null,
          },
          parent_ids: ["id-26", "id-35", "id-36"],
        },
        messageId: "id-32",
      },
      {
        type: "STATE_SNAPSHOT",
        rawEvent: {
          event: "on_chain_end",
          data: shared2,
          run_id: "id-38",
          name: "call_model",
          tags: ["seq:step:1"],
          metadata: shared19,
          parent_ids: ["id-26", "id-35"],
        },
        snapshot: shared14,
      },
      {
        type: "STATE_SNAPSHOT",
        rawEvent: {
          event: "on_chain_end",
          data: shared2,
          run_id: "id-35",
          name: "agent",
          tags: ["graph:step:8"],
          metadata: shared19,
          parent_ids: ["id-26"],
        },
        snapshot: shared14,
      },
      {
        type: "STEP_FINISHED",
        stepName: "agent",
      },
      {
        type: "STATE_SNAPSHOT",
        snapshot: {
          messages: [
            {
              content: "What's the weather like in San Francisco?",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-4",
              tool_calls: [
                {
                  name: "get_weather",
                  args: {
                    location: "San Francisco",
                  },
                  id: "id-5",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: shared1,
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: "get_weather",
              id: "id-19",
              tool_call_id: "id-5",
              artifact: null,
              status: "success",
            },
            {
              content: "Done! I've completed that for you.",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-14",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: "Tell me about the weather in New York.",
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-22",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-23",
              tool_calls: [
                {
                  name: "get_weather",
                  args: {
                    location: "San Francisco",
                  },
                  id: "id-5",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
            {
              content: shared1,
              additional_kwargs: {},
              response_metadata: {},
              type: "tool",
              name: "get_weather",
              id: "id-37",
              tool_call_id: "id-5",
              artifact: null,
              status: "success",
            },
            {
              content: "Done! I've completed that for you.",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "stop",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-32",
              tool_calls: [],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
          ],
        },
      },
      {
        type: "MESSAGES_SNAPSHOT",
        messages: [
          shared27,
          shared22,
          shared23,
          {
            id: "id-14",
            role: "assistant",
            content: "Done! I've completed that for you.",
          },
          {
            id: "id-22",
            role: "user",
            content: "Tell me about the weather in New York.",
          },
          {
            id: "id-23",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-5",
                type: "function",
                function: {
                  name: "get_weather",
                  arguments: '{"location": "San Francisco"}',
                },
              },
            ],
          },
          {
            id: "id-37",
            content: shared1,
            role: "tool",
            toolCallId: "id-5",
          },
          {
            id: "id-32",
            role: "assistant",
            content: "Done! I've completed that for you.",
          },
        ],
      },
      {
        type: "RUN_FINISHED",
        threadId: "id-1",
        runId: "id-21",
      },
    ],
  },
);
