import { defineEventTrace } from "../../event-trace-test";

// Generated by the event trace updater.
// Reason: Align traces with current main after merged checkpoint-pinned boundary snapshots; keep environment version metadata normalized
// Before accepting changes, verify whether the implementation regressed.
const shared1 = {
  type: "STATE_SNAPSHOT",
  snapshot: {
    messages: [
      {
        content: 'Generate Haiku for "I will always win"',
        additional_kwargs: {},
        response_metadata: {},
        type: "human",
        name: null,
        id: "id-3",
      },
      {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-4",
        tool_calls: [
          {
            name: "generate_haiku",
            args: {
              japanese: [
                "å‹åˆ©ã®é“ã‚’",
                "å¸¸ã«æ­©ã¿ç¶šã‘ã‚‹",
                "å‹ã¤é‹å‘½ã‚ˆ",
              ],
              english: [
                "On the path of victory",
                "I will always keep walking",
                "Destined to always win",
              ],
              image_name:
                "Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg",
              gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
            },
            id: "id-5",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
    ],
    tools: [
      {
        name: "generate_haiku",
        description: "",
        parameters: {
          type: "object",
          properties: {
            japanese: {
              type: "array",
              items: {
                type: "string",
              },
              description: "3 lines of haiku in Japanese",
            },
            english: {
              type: "array",
              items: {
                type: "string",
              },
              description: "3 lines of haiku translated to English",
            },
            image_name: {
              type: "string",
              description:
                "One relevant image name from: Osaka_Castle_Turret_Stone_Wall_Pine_Trees_Daytime.jpg, Tokyo_Skyline_Night_Tokyo_Tower_Mount_Fuji_View.jpg, Itsukushima_Shrine_Miyajima_Floating_Torii_Gate_Sunset_Long_Exposure.jpg, Takachiho_Gorge_Waterfall_River_Lush_Greenery_Japan.jpg, Bonsai_Tree_Potted_Japanese_Art_Green_Foliage.jpeg, Shirakawa-go_Gassho-zukuri_Thatched_Roof_Village_Aerial_View.jpg, Ginkaku-ji_Silver_Pavilion_Kyoto_Japanese_Garden_Pond_Reflection.jpg, Senso-ji_Temple_Asakusa_Cherry_Blossoms_Kimono_Umbrella.jpg, Cherry_Blossoms_Sakura_Night_View_City_Lights_Japan.jpg, Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg",
            },
            gradient: {
              type: "string",
              description: "CSS Gradient color for the background",
            },
          },
          required: ["japanese", "english", "image_name", "gradient"],
        },
      },
    ],
  },
} as const;
const shared2 = {
  type: "TOOL_CALL_END",
  rawEvent: {
    event: "on_chat_model_end",
    data: {
      output: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          finish_reason: "tool_calls",
          model_name: "gpt-4.1-mini",
          model_provider: "openai",
        },
        type: "ai",
        name: null,
        id: "id-4",
        tool_calls: [
          {
            name: "generate_haiku",
            args: {
              japanese: [
                "å‹åˆ©ã®é“ã‚’",
                "å¸¸ã«æ­©ã¿ç¶šã‘ã‚‹",
                "å‹ã¤é‹å‘½ã‚ˆ",
              ],
              english: [
                "On the path of victory",
                "I will always keep walking",
                "Destined to always win",
              ],
              image_name:
                "Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg",
              gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
            },
            id: "id-5",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
      },
      input: {
        messages: [
          [
            {
              content:
                "Help the user with writing Haikus. If the user asks for a haiku, use the generate_haiku tool to display the haiku to the user.",
              additional_kwargs: {},
              response_metadata: {},
              type: "system",
              name: null,
              id: null,
            },
            {
              content: 'Generate Haiku for "I will always win"',
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
          ],
        ],
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
} as const;
const shared3 = {
  type: "RUN_STARTED",
  threadId: "id-1",
  runId: "id-2",
  input: {
    threadId: "id-1",
    runId: "id-2",
    state: {},
    messages: [
      {
        id: "id-3",
        role: "user",
        content: 'Generate Haiku for "I will always win"',
      },
    ],
    tools: [
      {
        name: "generate_haiku",
        description: "",
        parameters: {
          type: "object",
          properties: {
            japanese: {
              type: "array",
              items: {
                type: "string",
              },
              description: "3 lines of haiku in Japanese",
            },
            english: {
              type: "array",
              items: {
                type: "string",
              },
              description: "3 lines of haiku translated to English",
            },
            image_name: {
              type: "string",
              description:
                "One relevant image name from: Osaka_Castle_Turret_Stone_Wall_Pine_Trees_Daytime.jpg, Tokyo_Skyline_Night_Tokyo_Tower_Mount_Fuji_View.jpg, Itsukushima_Shrine_Miyajima_Floating_Torii_Gate_Sunset_Long_Exposure.jpg, Takachiho_Gorge_Waterfall_River_Lush_Greenery_Japan.jpg, Bonsai_Tree_Potted_Japanese_Art_Green_Foliage.jpeg, Shirakawa-go_Gassho-zukuri_Thatched_Roof_Village_Aerial_View.jpg, Ginkaku-ji_Silver_Pavilion_Kyoto_Japanese_Garden_Pond_Reflection.jpg, Senso-ji_Temple_Asakusa_Cherry_Blossoms_Kimono_Umbrella.jpg, Cherry_Blossoms_Sakura_Night_View_City_Lights_Japan.jpg, Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg",
            },
            gradient: {
              type: "string",
              description: "CSS Gradient color for the background",
            },
          },
          required: ["japanese", "english", "image_name", "gradient"],
        },
      },
    ],
    context: [],
    forwardedProps: {},
  },
} as const;
const shared4 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: ',"å¸¸ã«æ­©ã¿ç¶šã‘ã‚‹","å‹ã¤é‹å‘½ã‚ˆ"],',
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: ',"å¸¸ã«æ­©ã¿ç¶šã‘ã‚‹","å‹ã¤é‹å‘½ã‚ˆ"],',
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: ',"å¸¸ã«æ­©ã¿ç¶šã‘ã‚‹","å‹ã¤é‹å‘½ã‚ˆ"],',
} as const;
const shared5 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [
          {
            name: "",
            args: {
              japanese: ["å‹åˆ©ã®é“ã‚’"],
            },
            id: null,
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: '{"japanese":["å‹åˆ©ã®é“ã‚’"',
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: '{"japanese":["å‹åˆ©ã®é“ã‚’"',
} as const;
const shared6 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: 'g.jpg","gradient":"l',
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: 'g.jpg","gradient":"l',
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: 'g.jpg","gradient":"l',
} as const;
const shared7 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: '"english":["On the p',
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: '"english":["On the p',
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: '"english":["On the p',
} as const;
const shared8 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: 'ath of victory","I w',
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: 'ath of victory","I w',
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: 'ath of victory","I w',
} as const;
const shared9 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: 'ing","Destined to al',
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: 'ing","Destined to al',
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: 'ing","Destined to al',
} as const;
const shared10 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: 'me":"Mount_Fuji_Lake',
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: 'me":"Mount_Fuji_Lake',
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: 'me":"Mount_Fuji_Lake',
} as const;
const shared11 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: 'ways win"],"image_na',
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: 'ways win"],"image_na',
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: 'ways win"],"image_na',
} as const;
const shared12 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: "_Reflection_Cherry_B",
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: "_Reflection_Cherry_B",
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: "_Reflection_Cherry_B",
} as const;
const shared13 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: "g, #667eea 0%, #764b",
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: "g, #667eea 0%, #764b",
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: "g, #667eea 0%, #764b",
} as const;
const shared14 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: "ill always keep walk",
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: "ill always keep walk",
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: "ill always keep walk",
} as const;
const shared15 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: "inear-gradient(135de",
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: "inear-gradient(135de",
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: "inear-gradient(135de",
} as const;
const shared16 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: "lossoms_Sakura_Sprin",
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: "lossoms_Sakura_Sprin",
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: "lossoms_Sakura_Sprin",
} as const;
const shared17 = {
  type: "TOOL_CALL_START",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [
          {
            name: "generate_haiku",
            args: {},
            id: "id-5",
            type: "tool_call",
          },
        ],
        invalid_tool_calls: [],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: "generate_haiku",
            args: "",
            id: "id-5",
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  toolCallName: "generate_haiku",
  parentMessageId: "id-4",
} as const;
const shared18 = {
  type: "TOOL_CALL_ARGS",
  rawEvent: {
    event: "on_chat_model_stream",
    data: {
      chunk: {
        content: "",
        additional_kwargs: {},
        response_metadata: {
          model_provider: "openai",
        },
        type: "AIMessageChunk",
        name: null,
        id: "id-4",
        tool_calls: [],
        invalid_tool_calls: [
          {
            name: null,
            args: 'a2 100%)"}',
            id: null,
            error: null,
            type: "invalid_tool_call",
          },
        ],
        usage_metadata: null,
        tool_call_chunks: [
          {
            name: null,
            args: 'a2 100%)"}',
            id: null,
            index: 0,
            type: "tool_call_chunk",
          },
        ],
        chunk_position: null,
      },
    },
    run_id: "id-6",
    name: "ChatOpenAI",
    tags: ["seq:step:1"],
    metadata: {
      thread_id: "id-1",
      ls_integration: "langchain_chat_model",
      langgraph_step: 1,
      langgraph_node: "chat_node",
      langgraph_triggers: ["branch:to:chat_node"],
      langgraph_path: ["__pregel_pull", "chat_node"],
      langgraph_checkpoint_ns: "chat_node:id-7",
      checkpoint_ns: "chat_node:id-7",
      ls_provider: "openai",
      ls_model_name: "gpt-4.1-mini",
      ls_model_type: "chat",
      ls_temperature: null,
    },
    parent_ids: ["id-8", "id-9"],
  },
  toolCallId: "id-5",
  delta: 'a2 100%)"}',
} as const;
const shared19 = {
  type: "MESSAGES_SNAPSHOT",
  messages: [
    {
      id: "id-3",
      role: "user",
      content: 'Generate Haiku for "I will always win"',
    },
    {
      id: "id-4",
      role: "assistant",
      content: "",
      toolCalls: [
        {
          id: "id-5",
          type: "function",
          function: {
            name: "generate_haiku",
            arguments:
              '{"japanese": ["\\u52dd\\u5229\\u306e\\u9053\\u3092", "\\u5e38\\u306b\\u6b69\\u307f\\u7d9a\\u3051\\u308b", "\\u52dd\\u3064\\u904b\\u547d\\u3088"], "english": ["On the path of victory", "I will always keep walking", "Destined to always win"], "image_name": "Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg", "gradient": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"}',
          },
        },
      ],
    },
  ],
} as const;
const shared20 = {
  content: "",
  additional_kwargs: {},
  response_metadata: {
    finish_reason: "tool_calls",
    model_name: "gpt-4.1-mini",
    model_provider: "openai",
  },
  type: "ai",
  name: null,
  id: "id-13",
  tool_calls: [
    {
      name: "generate_haiku",
      args: {
        japanese: ["æœˆãŒè¼ã", "å¤œç©ºã«é™ã‹ã«æµ®ã‹ã¶", "å…‰ã®è©©ã‚ˆ"],
        english: [
          "The bright moon shining",
          "Floating quietly in night sky",
          "A poem of light",
        ],
        image_name: "Cherry_Blossoms_Sakura_Night_View_City_Lights_Japan.jpg",
        gradient:
          "linear-gradient(135deg, #0c3547 0%, #204f64 50%, #2d6187 100%)",
      },
      id: "id-14",
      type: "tool_call",
    },
  ],
  invalid_tool_calls: [],
  usage_metadata: null,
} as const;
const shared21 = {
  thread_id: "id-1",
  ls_integration: "langchain_chat_model",
  langgraph_step: 4,
  langgraph_node: "chat_node",
  langgraph_triggers: ["branch:to:chat_node"],
  langgraph_path: ["__pregel_pull", "chat_node"],
  langgraph_checkpoint_ns: "chat_node:id-16",
  checkpoint_ns: "chat_node:id-16",
  ls_provider: "openai",
  ls_model_name: "gpt-4.1-mini",
  ls_model_type: "chat",
  ls_temperature: null,
} as const;
const shared22 = {
  content: "Haiku generated!",
  additional_kwargs: {},
  response_metadata: {},
  type: "tool",
  name: null,
  id: "id-11",
  tool_call_id: "id-5",
  artifact: null,
  status: "success",
} as const;
const shared23 = {
  content: 'Generate Haiku for "The moon shines bright"',
  additional_kwargs: {},
  response_metadata: {},
  type: "human",
  name: null,
  id: "id-12",
} as const;
const shared24 = {
  id: "id-12",
  role: "user",
  content: 'Generate Haiku for "The moon shines bright"',
} as const;

export const toolBasedGenUIPageEventTrace = defineEventTrace(import.meta.url, {
  haikuGenerationAndDisplayVerification: [
    shared3,
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared17,
    shared5,
    shared4,
    shared7,
    shared8,
    shared14,
    shared9,
    shared11,
    shared10,
    shared12,
    shared16,
    shared6,
    shared15,
    shared13,
    shared18,
    shared2,
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    shared1,
    shared19,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
    },
  ],
  haikuGenerationAndUIConsistencyForTwoDifferentPrompts: [
    shared3,
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    shared17,
    shared5,
    shared4,
    shared7,
    shared8,
    shared14,
    shared9,
    shared11,
    shared10,
    shared12,
    shared16,
    shared6,
    shared15,
    shared13,
    shared18,
    shared2,
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    shared1,
    shared19,
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-2",
    },
    {
      type: "RUN_STARTED",
      threadId: "id-1",
      runId: "id-10",
      input: {
        threadId: "id-1",
        runId: "id-10",
        state: {
          messages: [
            {
              content: 'Generate Haiku for "I will always win"',
              additional_kwargs: {},
              response_metadata: {},
              type: "human",
              name: null,
              id: "id-3",
            },
            {
              content: "",
              additional_kwargs: {},
              response_metadata: {
                finish_reason: "tool_calls",
                model_name: "gpt-4.1-mini",
                model_provider: "openai",
              },
              type: "ai",
              name: null,
              id: "id-4",
              tool_calls: [
                {
                  name: "generate_haiku",
                  args: {
                    japanese: [
                      "å‹åˆ©ã®é“ã‚’",
                      "å¸¸ã«æ­©ã¿ç¶šã‘ã‚‹",
                      "å‹ã¤é‹å‘½ã‚ˆ",
                    ],
                    english: [
                      "On the path of victory",
                      "I will always keep walking",
                      "Destined to always win",
                    ],
                    image_name:
                      "Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg",
                    gradient:
                      "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
                  },
                  id: "id-5",
                  type: "tool_call",
                },
              ],
              invalid_tool_calls: [],
              usage_metadata: null,
            },
          ],
          tools: [
            {
              name: "generate_haiku",
              description: "",
              parameters: {
                type: "object",
                properties: {
                  japanese: {
                    type: "array",
                    items: {
                      type: "string",
                    },
                    description: "3 lines of haiku in Japanese",
                  },
                  english: {
                    type: "array",
                    items: {
                      type: "string",
                    },
                    description: "3 lines of haiku translated to English",
                  },
                  image_name: {
                    type: "string",
                    description:
                      "One relevant image name from: Osaka_Castle_Turret_Stone_Wall_Pine_Trees_Daytime.jpg, Tokyo_Skyline_Night_Tokyo_Tower_Mount_Fuji_View.jpg, Itsukushima_Shrine_Miyajima_Floating_Torii_Gate_Sunset_Long_Exposure.jpg, Takachiho_Gorge_Waterfall_River_Lush_Greenery_Japan.jpg, Bonsai_Tree_Potted_Japanese_Art_Green_Foliage.jpeg, Shirakawa-go_Gassho-zukuri_Thatched_Roof_Village_Aerial_View.jpg, Ginkaku-ji_Silver_Pavilion_Kyoto_Japanese_Garden_Pond_Reflection.jpg, Senso-ji_Temple_Asakusa_Cherry_Blossoms_Kimono_Umbrella.jpg, Cherry_Blossoms_Sakura_Night_View_City_Lights_Japan.jpg, Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg",
                  },
                  gradient: {
                    type: "string",
                    description: "CSS Gradient color for the background",
                  },
                },
                required: ["japanese", "english", "image_name", "gradient"],
              },
            },
          ],
        },
        messages: [
          {
            id: "id-4",
            role: "assistant",
            content: "",
            toolCalls: [
              {
                id: "id-5",
                type: "function",
                function: {
                  name: "generate_haiku",
                  arguments:
                    '{"japanese": ["\\u52dd\\u5229\\u306e\\u9053\\u3092", "\\u5e38\\u306b\\u6b69\\u307f\\u7d9a\\u3051\\u308b", "\\u52dd\\u3064\\u904b\\u547d\\u3088"], "english": ["On the path of victory", "I will always keep walking", "Destined to always win"], "image_name": "Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg", "gradient": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"}',
                },
              },
            ],
          },
          {
            id: "id-11",
            content: "Haiku generated!",
            role: "tool",
            toolCallId: "id-5",
          },
          shared24,
        ],
        tools: [
          {
            name: "generate_haiku",
            description: "",
            parameters: {
              type: "object",
              properties: {
                japanese: {
                  type: "array",
                  items: {
                    type: "string",
                  },
                  description: "3 lines of haiku in Japanese",
                },
                english: {
                  type: "array",
                  items: {
                    type: "string",
                  },
                  description: "3 lines of haiku translated to English",
                },
                image_name: {
                  type: "string",
                  description:
                    "One relevant image name from: Osaka_Castle_Turret_Stone_Wall_Pine_Trees_Daytime.jpg, Tokyo_Skyline_Night_Tokyo_Tower_Mount_Fuji_View.jpg, Itsukushima_Shrine_Miyajima_Floating_Torii_Gate_Sunset_Long_Exposure.jpg, Takachiho_Gorge_Waterfall_River_Lush_Greenery_Japan.jpg, Bonsai_Tree_Potted_Japanese_Art_Green_Foliage.jpeg, Shirakawa-go_Gassho-zukuri_Thatched_Roof_Village_Aerial_View.jpg, Ginkaku-ji_Silver_Pavilion_Kyoto_Japanese_Garden_Pond_Reflection.jpg, Senso-ji_Temple_Asakusa_Cherry_Blossoms_Kimono_Umbrella.jpg, Cherry_Blossoms_Sakura_Night_View_City_Lights_Japan.jpg, Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg",
                },
                gradient: {
                  type: "string",
                  description: "CSS Gradient color for the background",
                },
              },
              required: ["japanese", "english", "image_name", "gradient"],
            },
          },
        ],
        context: [],
        forwardedProps: {},
      },
    },
    {
      type: "STEP_STARTED",
      stepName: "chat_node",
    },
    {
      type: "TOOL_CALL_START",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [
              {
                name: "generate_haiku",
                args: {},
                id: "id-14",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: "generate_haiku",
                args: "",
                id: "id-14",
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      toolCallName: "generate_haiku",
      parentMessageId: "id-13",
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [
              {
                name: "",
                args: {
                  japanese: ["æœˆãŒè¼ã"],
                },
                id: null,
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: '{"japanese":["æœˆãŒè¼ã",',
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: '{"japanese":["æœˆãŒè¼ã",',
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: '"å¤œç©ºã«é™ã‹ã«æµ®ã‹ã¶","å…‰ã®è©©ã‚ˆ"],',
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: '"å¤œç©ºã«é™ã‹ã«æµ®ã‹ã¶","å…‰ã®è©©ã‚ˆ"],',
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: '"å¤œç©ºã«é™ã‹ã«æµ®ã‹ã¶","å…‰ã®è©©ã‚ˆ"],',
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: '"english":["The brig',
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: '"english":["The brig',
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: '"english":["The brig',
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: 'ht moon shining","Fl',
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: 'ht moon shining","Fl',
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: 'ht moon shining","Fl',
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: "oating quietly in ni",
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: "oating quietly in ni",
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: "oating quietly in ni",
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: 'ght sky","A poem of ',
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: 'ght sky","A poem of ',
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: 'ght sky","A poem of ',
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: 'light"],"image_name"',
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: 'light"],"image_name"',
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: 'light"],"image_name"',
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: ':"Cherry_Blossoms_Sa',
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: ':"Cherry_Blossoms_Sa',
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: ':"Cherry_Blossoms_Sa',
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: "kura_Night_View_City",
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: "kura_Night_View_City",
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: "kura_Night_View_City",
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: '_Lights_Japan.jpg","',
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: '_Lights_Japan.jpg","',
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: '_Lights_Japan.jpg","',
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: 'gradient":"linear-gr',
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: 'gradient":"linear-gr',
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: 'gradient":"linear-gr',
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: "adient(135deg, #0c35",
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: "adient(135deg, #0c35",
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: "adient(135deg, #0c35",
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: "47 0%, #204f64 50%, ",
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: "47 0%, #204f64 50%, ",
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: "47 0%, #204f64 50%, ",
    },
    {
      type: "TOOL_CALL_ARGS",
      rawEvent: {
        event: "on_chat_model_stream",
        data: {
          chunk: {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              model_provider: "openai",
            },
            type: "AIMessageChunk",
            name: null,
            id: "id-13",
            tool_calls: [],
            invalid_tool_calls: [
              {
                name: null,
                args: '#2d6187 100%)"}',
                id: null,
                error: null,
                type: "invalid_tool_call",
              },
            ],
            usage_metadata: null,
            tool_call_chunks: [
              {
                name: null,
                args: '#2d6187 100%)"}',
                id: null,
                index: 0,
                type: "tool_call_chunk",
              },
            ],
            chunk_position: null,
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
      delta: '#2d6187 100%)"}',
    },
    {
      type: "TOOL_CALL_END",
      rawEvent: {
        event: "on_chat_model_end",
        data: {
          output: shared20,
          input: {
            messages: [
              [
                {
                  content:
                    "Help the user with writing Haikus. If the user asks for a haiku, use the generate_haiku tool to display the haiku to the user.",
                  additional_kwargs: {},
                  response_metadata: {},
                  type: "system",
                  name: null,
                  id: null,
                },
                {
                  content: 'Generate Haiku for "I will always win"',
                  additional_kwargs: {},
                  response_metadata: {},
                  type: "human",
                  name: null,
                  id: "id-3",
                },
                {
                  content: "",
                  additional_kwargs: {},
                  response_metadata: {
                    finish_reason: "tool_calls",
                    model_name: "gpt-4.1-mini",
                    model_provider: "openai",
                  },
                  type: "ai",
                  name: null,
                  id: "id-4",
                  tool_calls: [
                    {
                      name: "generate_haiku",
                      args: {
                        japanese: [
                          "å‹åˆ©ã®é“ã‚’",
                          "å¸¸ã«æ­©ã¿ç¶šã‘ã‚‹",
                          "å‹ã¤é‹å‘½ã‚ˆ",
                        ],
                        english: [
                          "On the path of victory",
                          "I will always keep walking",
                          "Destined to always win",
                        ],
                        image_name:
                          "Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg",
                        gradient:
                          "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
                      },
                      id: "id-5",
                      type: "tool_call",
                    },
                  ],
                  invalid_tool_calls: [],
                  usage_metadata: null,
                },
                shared22,
                shared23,
              ],
            ],
          },
        },
        run_id: "id-15",
        name: "ChatOpenAI",
        tags: ["seq:step:1"],
        metadata: shared21,
        parent_ids: ["id-17", "id-18"],
      },
      toolCallId: "id-14",
    },
    {
      type: "STEP_FINISHED",
      stepName: "chat_node",
    },
    {
      type: "STATE_SNAPSHOT",
      snapshot: {
        messages: [
          {
            content: 'Generate Haiku for "I will always win"',
            additional_kwargs: {},
            response_metadata: {},
            type: "human",
            name: null,
            id: "id-3",
          },
          {
            content: "",
            additional_kwargs: {},
            response_metadata: {
              finish_reason: "tool_calls",
              model_name: "gpt-4.1-mini",
              model_provider: "openai",
            },
            type: "ai",
            name: null,
            id: "id-4",
            tool_calls: [
              {
                name: "generate_haiku",
                args: {
                  japanese: [
                    "å‹åˆ©ã®é“ã‚’",
                    "å¸¸ã«æ­©ã¿ç¶šã‘ã‚‹",
                    "å‹ã¤é‹å‘½ã‚ˆ",
                  ],
                  english: [
                    "On the path of victory",
                    "I will always keep walking",
                    "Destined to always win",
                  ],
                  image_name:
                    "Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg",
                  gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
                },
                id: "id-5",
                type: "tool_call",
              },
            ],
            invalid_tool_calls: [],
            usage_metadata: null,
          },
          shared22,
          shared23,
          shared20,
        ],
        tools: [
          {
            name: "generate_haiku",
            description: "",
            parameters: {
              type: "object",
              properties: {
                japanese: {
                  type: "array",
                  items: {
                    type: "string",
                  },
                  description: "3 lines of haiku in Japanese",
                },
                english: {
                  type: "array",
                  items: {
                    type: "string",
                  },
                  description: "3 lines of haiku translated to English",
                },
                image_name: {
                  type: "string",
                  description:
                    "One relevant image name from: Osaka_Castle_Turret_Stone_Wall_Pine_Trees_Daytime.jpg, Tokyo_Skyline_Night_Tokyo_Tower_Mount_Fuji_View.jpg, Itsukushima_Shrine_Miyajima_Floating_Torii_Gate_Sunset_Long_Exposure.jpg, Takachiho_Gorge_Waterfall_River_Lush_Greenery_Japan.jpg, Bonsai_Tree_Potted_Japanese_Art_Green_Foliage.jpeg, Shirakawa-go_Gassho-zukuri_Thatched_Roof_Village_Aerial_View.jpg, Ginkaku-ji_Silver_Pavilion_Kyoto_Japanese_Garden_Pond_Reflection.jpg, Senso-ji_Temple_Asakusa_Cherry_Blossoms_Kimono_Umbrella.jpg, Cherry_Blossoms_Sakura_Night_View_City_Lights_Japan.jpg, Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg",
                },
                gradient: {
                  type: "string",
                  description: "CSS Gradient color for the background",
                },
              },
              required: ["japanese", "english", "image_name", "gradient"],
            },
          },
        ],
      },
    },
    {
      type: "MESSAGES_SNAPSHOT",
      messages: [
        {
          id: "id-3",
          role: "user",
          content: 'Generate Haiku for "I will always win"',
        },
        {
          id: "id-4",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-5",
              type: "function",
              function: {
                name: "generate_haiku",
                arguments:
                  '{"japanese": ["\\u52dd\\u5229\\u306e\\u9053\\u3092", "\\u5e38\\u306b\\u6b69\\u307f\\u7d9a\\u3051\\u308b", "\\u52dd\\u3064\\u904b\\u547d\\u3088"], "english": ["On the path of victory", "I will always keep walking", "Destined to always win"], "image_name": "Mount_Fuji_Lake_Reflection_Cherry_Blossoms_Sakura_Spring.jpg", "gradient": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"}',
              },
            },
          ],
        },
        {
          id: "id-11",
          content: "Haiku generated!",
          role: "tool",
          toolCallId: "id-5",
        },
        shared24,
        {
          id: "id-13",
          role: "assistant",
          content: "",
          toolCalls: [
            {
              id: "id-14",
              type: "function",
              function: {
                name: "generate_haiku",
                arguments:
                  '{"japanese": ["\\u6708\\u304c\\u8f1d\\u304f", "\\u591c\\u7a7a\\u306b\\u9759\\u304b\\u306b\\u6d6e\\u304b\\u3076", "\\u5149\\u306e\\u8a69\\u3088"], "english": ["The bright moon shining", "Floating quietly in night sky", "A poem of light"], "image_name": "Cherry_Blossoms_Sakura_Night_View_City_Lights_Japan.jpg", "gradient": "linear-gradient(135deg, #0c3547 0%, #204f64 50%, #2d6187 100%)"}',
              },
            },
          ],
        },
      ],
    },
    {
      type: "RUN_FINISHED",
      threadId: "id-1",
      runId: "id-10",
    },
  ],
});
