package com.agui.community.core.message;

import java.util.List;
import java.util.Objects;

/**
 * A message generated by the assistant (the agent). Both the textual
 * {@link #content()} and any {@link #toolCalls()} are optional, but at least
 * one is typically present.
 *
 * @param id        the unique identifier of this message (required)
 * @param content   the textual content of this message, or {@code null}
 * @param name      an optional name for the participant, or {@code null}
 * @param toolCalls the tool calls requested by the assistant; never
 *                  {@code null} (defaults to an empty, unmodifiable list)
 * @see <a href="https://docs.ag-ui.com/concepts/messages">AG-UI Messages</a>
 */
public record AssistantMessage(String id, String content, String name, List<ToolCall> toolCalls)
        implements Message {

    public AssistantMessage {
        Objects.requireNonNull(id, "id must not be null");
        toolCalls = Objects.isNull(toolCalls) ? List.of() : List.copyOf(toolCalls);
    }

    /**
     * Creates an assistant message with only textual content.
     *
     * @param id      the unique identifier of this message
     * @param content the textual content of this message
     */
    public AssistantMessage(String id, String content) {
        this(id, content, null, List.of());
    }

    @Override
    public Role role() {
        return Role.ASSISTANT;
    }
}
